### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by ibaranov-cp** [alexa-pi/AlexaPi#91] opened 2016-11-13 22:54 UTC
Hey all,
On my install on a Pi3 with Ubuntu Mate 16.04, the following are required during install and use, but had to be done manually for some reason:

cherrypy (pip)
webrtcvad (pip)
python-memcache (apt-get)
pocketsphinx (pip)

Just thought to note it for people

**Comment by ibaranov-cp** [comment] 2016-11-14 13:57
Yes, via the setup script.

Currently away from the device, will do asap.

**Comment by renekliment** [comment] 2016-11-19 10:19
So I did an install yesterday on Ubuntu (Armbian actually) and the package `python-setuptools` wasn't installed by default, so the _pip_ commands failed. So now I don't think it's caused by a different default py/pip version (set to 3), but by just that. 
I suppose you got some error during the setup, right?

I'm confident it's fixed in #82 and since we don't officially support installation on anything else than Raspbian now (will be solved by the #82), I'm closing this now.

Thanks for the report! It didn't occur to me that some packages were not installed there by default.

**Closed by renekliment** 2016-11-19 10:19 UTC
