### ISSUE TITLE
Alexa Responds only 3 times then stops + Choppy Audio

### ISSUE THREAD

**Issue by LoganPi3** [alexa-pi/AlexaPi#273] opened 2017-06-27 16:03 UTC
**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
Raspbian Pixel (Newest as of 6/25/17)

**Your hardware platform and model you are running on:**
```
Raspberry Pi 3 Model B
```

**Python release (`python2 --version`):**
```
Newest Version (Asof 6/25/17)
```

**Description of problem:**
```
When I boot it up, I say Alexa into the usb microphone, and she replies with "Yes?" so I say another command like "What time is it?" and she doesn't respond and I try "Alexa" again and I get nothing, so I open the LXTerminal and I type "sudo systemctl status AlexaPi.service" and I get the whole service thing says that its running and working, but the last line is "raspberrypi python[605]: [6e6004d8] alsa audio output error: cannot estimate delay: Input/output error"
Plus, when she says Yes? or Hello, it is either choppy or delayed. Can you help? Thanks
```

**Comment by EmerickH** [comment] 2017-07-21 14:47
Duplicate of #100:

> Hey!
> 
> `alsa audio output error: cannot estimate delay: Input/output error`
> This is normal, just ignore it.
> 
> Check your configuration.yaml to make sure you have correct audio devices set up. There is currently a bug in master that sets it up incorrectly. See #98 (comment)

Please provide more information like your `config.yaml`.

Emerick

**Comment by renekliment** [comment] 2017-10-14 20:46
Closing due to inactivity. Feel free to reopen.

**Closed by renekliment** 2017-10-14 20:46 UTC
Labels: audio, duplicate
