### ISSUE TITLE
My Alexa Skill works on simulator and echo but not on AlexaPi

### ISSUE THREAD

**Issue by bryantkhoo** [alexa-pi/AlexaPi#399] opened 2018-05-10 08:07 UTC
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
```
Raspbian Jessie
```

**Your hardware platform and model you are running on:**
```
Raspberry Pi 3
```

**Python release (`python2 --version`):**
```
2.7.9
```

**Description of problem:**
```
My Alexa skills works perfectly on the test simulator and echo dot.
But on the Raspberry Pi running AlexaPi, the session of the skill does not seem to be able to persist after initial invocation/launching of the skill. 
```

**Expected:**
```

```

**Additional info:**
```

```

**Comment by EmerickH** [comment] 2018-07-19 12:43
Duplicate of #391

**Closed by EmerickH** 2018-07-19 12:43 UTC
Labels: API v1 limitation
