### ISSUE TITLE
Can you update to the new API?

### ISSUE THREAD

**Issue by Cole128** [alexa-pi/AlexaPi#340] opened 2017-11-05 14:30 UTC
I think the old API may not be supported by Amazon anymore, and may be causing #331.

**Comment by renekliment** [comment] 2017-11-05 15:52
Duplicate of #50

**Closed by renekliment** 2017-11-05 15:52 UTC

**Comment by Cole128** [comment] 2017-11-05 15:54
Of course, sorry.

**Comment by aussiemax** [comment] 2018-04-06 03:33
Firstly this is a great project! Combining AlexaPi with Shairport-sync.... Genius!
Do you have a timeline of when you move to the new API?
