### ISSUE TITLE
install fails on missing vlc-nox

### ISSUE THREAD

**Issue by thambu1710** [alexa-pi/AlexaPi#467] opened 2019-07-29 11:58 UTC
i am runing raspberry pi latest version 
i need help today its urgent 
pls improve the setup.sh code

**Comment by erikhermesman** [comment] 2019-08-03 17:52
Edit this file:

AlexaPi/src/scripts/inc/os/debian.sh

and replace vlc-nox with vlc-bin

The source of this information came from [https://github.com/alexa-pi/AlexaPi/issues/436](https://github.com/alexa-pi/AlexaPi/issues/436)

**Comment by EmerickH** [comment] 2019-08-06 12:53
Duplicate of #436

**Closed by EmerickH** 2019-08-06 12:53 UTC
