### ISSUE TITLE
HTTP ERROR 500. This Page isn't working, Localhost is currently unable to handle this request.

### ISSUE THREAD

**Issue by skkuvind** [alexa-pi/AlexaPi#423] opened 2018-10-12 08:25 UTC
Thank you for reporting an issue with **AlexaPi**.

Make sure you are running the latest version of **AlexaPi**, and look through [issues](https://github.com/alexa-pi/AlexaPi/issues?utf8=%E2%9C%93&q=is%3Aissue) before submitting.

Check out our [Wiki](https://github.com/alexa-pi/AlexaPi/wiki/), and make sure to look at [Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/), and [Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging) in particular before filing an issue.

In order to help troubleshooting, be sure to include the following information:

**Output of the [audio debugging script](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging#audio-debugging-script).**

**Your OS (including version) where you are running AlexaPi:**
```Rasbpian
```

**Your hardware platform and model you are running on:**
```RaspberryPI3

```

**Python release (`python2 --version`):**
```Python2 - 2.7.13  & Python3 - 3.5.3

```

**Description of problem:**
```After installation of code when i it says: "Ready goto http://myipaddress:5050 or http://localhost:5050  to begin the auth process" and i open the browser it gives an error in browser as listed above.

```

**Expected:**
```to open amazon login page for auth process.

```

**Problem-relevant `config.yaml` entries:**
```unable to find config.yaml file in directory, instead of i got a file named as "config.template.yaml", which has no entry in it like: client id, slient secret id n all

```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by lucbors** [comment] 2018-10-12 12:00
Take a look here: https://github.com/alexa-pi/AlexaPi/issues/420#issuecomment-429301592
It might work for you too. In my case the 500 is caused by an error when running the auth_web.py. After installing another library, it worked for me

**Comment by Marcreed48** [comment] 2018-10-20 23:45
I JUST resolved the same problem. Raspbian Stretch, RPI3 B, fresh install AlexaPi. After receiving the http error 500, I logged into ‘developer.amazon.com’. Then opened a new tab and tried accessing my RPI again, now it asked to connect, but another error screen. Then I forgot to keep the command line open for yaml (keep it running) then open ‘sudo nano’ (another screen on pi) to see your secret and security numbers. I had a ‘5’ instead of a ‘6’ after that, I tried looking up my IP address again and it said ‘success!’

**Comment by Marcreed48** [comment] 2018-10-20 23:47
Sorry it’s not more detailed, ask me and I’ll detail it.

**Comment by frappesc** [comment] 2018-10-31 10:32
can you please give more detailed instruction? i still cannot make it works

**Comment by renekliment** [comment] 2018-12-22 12:49
Not enough details.

Try now with the latest version, which has some dependency fixes. If it still doesn't work, you can try running the `auth_web.py` with a debug flag to see what's going to.

Closing for now, feel free to reopen.

**Closed by renekliment** 2018-12-22 12:49 UTC
