### ISSUE TITLE
Not restarting when internet connection shutter

### ISSUE THREAD

**Issue by usamitysam** [alexa-pi/AlexaPi#259] opened 2017-06-13 02:31 UTC
**Your OS (including version) where you are running AlexaPi:**
Raspbian 8 (jessie)

**Your hardware platform and model you are running on:**
```
Raspberry Pi ?
```

**Python release (`python2 --version`):**
```
Python 2.7.9
```

**Description of problem:**
```
AlexaPi hangs with ConnectionError when there is a poorly timed Alexa request when the microwave is started.  The OS does not believe it is crashed. Status query returns "active (running)", but Alexa won't respond and the green LED is stuck on.

The issue isn't entirely unexpected as the 2.4Ghz from the microwave temporarily kills the raspberry pi's wifi.  However it would be good to harden the code and retry when this happens.
```

**Expected:**
```
Retry not hang
```

**Steps to reproduce:**

1. Trigger Alexa 
2. Start the microwave

**Traceback (if applicable):**
```
Jun 12 17:27:41 echopi python[693]: INFO: AVS token: Obtained successfully
Jun 12 18:16:17 echopi python[693]: Exception in thread Thread-104:
Jun 12 18:16:17 echopi python[693]: Traceback (most recent call last):
Jun 12 18:16:17 echopi python[693]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Jun 12 18:16:17 echopi python[693]: self.run()
Jun 12 18:16:17 echopi python[693]: File "/usr/lib/python2.7/threading.py", line 763, in run
Jun 12 18:16:17 echopi python[693]: self.__target(*self.__args, **self.__kwargs)
Jun 12 18:16:17 echopi python[693]: File "/opt/AlexaPi/src/main.py", line 542, in trigger_process
Jun 12 18:16:17 echopi python[693]: alexa_speech_recognizer(audio_stream)
Jun 12 18:16:17 echopi python[693]: File "/opt/AlexaPi/src/main.py", line 347, in alexa_speech_recognizer
Jun 12 18:16:17 echopi python[693]: resp = requests.post(url, headers=headers, data=data)
Jun 12 18:16:17 echopi python[693]: File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
Jun 12 18:16:17 echopi python[693]: return request('post', url, data=data, json=json, **kwargs)
Jun 12 18:16:17 echopi python[693]: File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
Jun 12 18:16:17 echopi python[693]: return session.request(method=method, url=url, **kwargs)
Jun 12 18:16:17 echopi python[693]: File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 513, in request
Jun 12 18:16:17 echopi python[693]: resp = self.send(prep, **send_kwargs)
Jun 12 18:16:17 echopi python[693]: File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
Jun 12 18:16:17 echopi python[693]: r = adapter.send(request, **kwargs)
Jun 12 18:16:17 echopi python[693]: File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
Jun 12 18:16:17 echopi python[693]: raise ConnectionError(err, request=request)
Jun 12 18:16:17 echopi python[693]: ConnectionError: [Errno 110] Connection timed out
```

**Additional info:**
```
The service must be stopped and restarted in order to recover
```

**Comment by EmerickH** [comment] 2017-06-16 14:28
@usamitysam personally, when I unplug my Ethernet cable, it just searches for the Amazon server and finally find it when I re-plug the cable but don't show any error message.
Are you sure to have the last version?
```
cd /opt/AlexaPi/src/
sudo git pull origin master
```

Emerick

**Comment by renekliment** [comment] 2017-06-16 14:32
@usamitysam I thing this is a bug on the microwave front. Have you tried opening an issue on their GItHub repo? Is this a know bug? Have you tried updating your microwave?

On a more serious note, yes, AlexaPi should handle this, we have #159 for that, but no one had time to look at it. Closing as a duplicate of that.

P.S.: Probably the most hillarious bug report here at AlexaPi :-)

**Closed by renekliment** 2017-06-16 14:32 UTC
Labels: bug, help wanted
